# Generated by Django 4.2.16 on 2024-09-27 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactform_sent_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'ordering': ['sent_on']},
        ),
    ]
