# Generated by Django 4.2.16 on 2024-10-04 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-day']},
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='day',
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('day', 'time')},
        ),
    ]
